"""empty message

Revision ID: 2e960e36c4d1
Revises: cbd3d4ff3d94
Create Date: 2020-09-29 17:08:26.006212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e960e36c4d1'
down_revision = 'cbd3d4ff3d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_status_name_key', 'service_status', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('service_status_name_key', 'service_status', ['name'])
    # ### end Alembic commands ###
