"""empty message

Revision ID: fb5285665b1c
Revises: 27e7592da7ca
Create Date: 2020-09-30 11:56:28.987611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5285665b1c'
down_revision = '27e7592da7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'host', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'host_id')
    # ### end Alembic commands ###
